import Foundation

enum ConfigurationCoverage {
    static let settingsRules: [String: ConfigurationRule] = [
        "compactMode": .flag,
        "showFavoritesInCompactMode": .flag,
        "openOnCursorScreen": .flag,
        "paletteDraggable": .flag,
        "customCommandsShowInLauncher": .flag,
        "windowManagementEnabled": .flag,
        "windowManagementShowInLauncher": .flag,
        "windowCycle": .strings(["off", "sizes", "displays"]),
        "windowLayoutsShowInLauncher": .flag,
        "quicklinksEnabled": .flag,
        "quicklinksShowInLauncher": .flag,
        "quicklinkOpensNewWindow": .flag,
        "quicklinkConfirmsBeforeDelete": .flag,
        "calendarShowInLauncher": .flag,
        "calendarIncludesTomorrow": .flag,
        "menuBarLinkedEventsOnly": .flag,
        "supportReminders": .flag,
        "showInMenuBar": .flag,
        "escapeKeyBehavior": .strings(["navigateBackOrClose", "closeAndPopToRoot"]),
        "paletteTransparency": .number(-100...100, integer: true),
        "appearance": .strings(["system", "dark", "light"]),
        "emojiSkinTone": .strings(["none", "light", "mediumLight", "medium", "mediumDark", "dark"]),
        "quicklinkSelectionFallback": .strings(["ask", "clipboard"]),
        "popToRootSeconds": .integers([0, 5, 15, 30, 60, 90]),
        "calendarLauncherLimit": .integers([0, 1, 3, 5]),
        "joinWindowMinutes": .integers([1, 2, 5, 10, 15]),
        "menuBarEvents": .integers([0, 2, 5, 10, 30]),
        "calendarMenuBarDisplay": .integers([0, 1, 2]),
        "hideCurrentEvent": .integers([-1, 0, 5, 10, 30]),
        "windowGap": .number(0...100, integer: true)
    ]

    static let defaults: [String: ConfigurationValue] = [
        "compactMode": .bool(false),
        "showFavoritesInCompactMode": .bool(true),
        "openOnCursorScreen": .bool(true),
        "paletteDraggable": .bool(false),
        "customCommandsShowInLauncher": .bool(true),
        "windowManagementEnabled": .bool(false),
        "windowManagementShowInLauncher": .bool(true),
        "windowCycle": .string("off"),
        "windowLayoutsShowInLauncher": .bool(true),
        "quicklinksEnabled": .bool(false),
        "quicklinksShowInLauncher": .bool(true),
        "quicklinkOpensNewWindow": .bool(false),
        "quicklinkConfirmsBeforeDelete": .bool(true),
        "calendarShowInLauncher": .bool(true),
        "calendarIncludesTomorrow": .bool(true),
        "menuBarLinkedEventsOnly": .bool(true),
        "supportReminders": .bool(true),
        "showInMenuBar": .bool(true),
        "escapeKeyBehavior": .string("navigateBackOrClose"),
        "appearance": .string("system"),
        "paletteTransparency": .number(0),
        "emojiSkinTone": .string("none"),
        "quicklinkSelectionFallback": .string("ask"),
        "popToRootSeconds": .number(0),
        "calendarLauncherLimit": .number(3),
        "joinWindowMinutes": .number(5),
        "menuBarEvents": .number(0),
        "calendarMenuBarDisplay": .number(0),
        "hideCurrentEvent": .number(-1),
        "windowGap": .number(0)
    ]

    static let included: [AppSettingsKey] = [
        .compactMode,
        .showFavoritesInCompactMode,
        .openOnCursorScreen,
        .paletteDraggable,
        .customCommandsShowInLauncher,
        .windowManagementEnabled,
        .windowManagementShowInLauncher,
        .windowCycle,
        .windowLayoutsShowInLauncher,
        .quicklinksEnabled,
        .quicklinksShowInLauncher,
        .quicklinkOpensNewWindow,
        .quicklinkConfirmsBeforeDelete,
        .calendarShowInLauncher,
        .calendarIncludesTomorrow,
        .menuBarLinkedEventsOnly,
        .supportReminders,
        .escapeKeyBehavior,
        .appearance,
        .paletteTransparency,
        .emojiSkinTone,
        .quicklinkSelectionFallback,
        .popToRootTimeout,
        .calendarLauncherLimit,
        .joinWindowMinutes,
        .menuBarEvents,
        .calendarMenuBarDisplay,
        .hideCurrentEvent,
        .windowGap
    ]

    static let excluded: [AppSettingsKey: String] = [
        .interfaceSize: "Local interface sizing.",
        .emojiGridColumns: "Local emoji grid sizing.",
        .notesRendersMarkdown: "Local notes presentation.",
        .notesShowsFormattingBar: "Local notes presentation.",
        .navigationEnabled: "Local navigation capability.",
        .menuSearchDisabledApps: "Local menu search policy.",
        .menuSearchShowsAppleMenu: "Local menu search policy.",
        .appleShortcutsEnabled: "Local executable shortcuts and consent.",
        .quickActionModelOverrides: "Local AI model selection.",
        .clipboardEnabled: "Local clipboard capture policy and data.",
        .clipboardTextSearchEnabled: "Text recognition must be enabled on each Mac.",
        .clipboardRetention: "Local clipboard capture policy and data.",
        .clipboardDefaultAction: "Local clipboard capture policy and data.",
        .clipboardDisabledApps: "Local clipboard capture policy and data.",
        .hyperKey: "Local physical keyboard remapping and input sources.",
        .hyperKeyIncludesShift: "Local physical keyboard remapping and input sources.",
        .hyperKeyQuickPress: "Local physical keyboard remapping and input sources.",
        .autoSwitchInputSource: "Local physical keyboard remapping and input sources.",
        .searchScopes: "Machine-specific search roots and policy.",
        .fileSearchEnabled: "Machine-specific search roots and policy.",
        .fileSearchScopes: "Machine-specific search roots and policy.",
        .fileSearchIgnorePatterns: "Machine-specific search roots and policy.",
        .palettePosition: "Local window geometry.",
        .notesEnabled: "Local notes and snippet data and capability settings.",
        .snippetsEnabled: "Local notes and snippet data and capability settings.",
        .snippetsShowInLauncher: "Local notes and snippet data and capability settings.",
        .customCommandsEnabled: "Executing shell commands must be enabled on each Mac.",
        .extensionsEnabled: "Local extension code, registries and toolchain.",
        .extensionsShowInLauncher: "Local extension code, registries and toolchain.",
        .extensionPackageManager: "Local extension code, registries and toolchain.",
        .extensionRegistries: "Local extension code, registries and toolchain.",
        .extensionCustomSearchPaths: "Local extension code, registries and toolchain.",
        .calendarEnabled: "Local calendar, unattended actions and camera consent.",
        .autoJoinMeetings: "Local calendar, unattended actions and camera consent.",
        .autoJoinConfirms: "Local calendar, unattended actions and camera consent.",
        .cameraPreview: "Local calendar, unattended actions and camera consent.",
        .aiEnabled: "Local AI connections, credentials, instructions and histories.",
        .aiInstalledProviders: "Local AI connections, credentials, instructions and histories.",
        .aiConnections: "Local AI connections, credentials, instructions and histories.",
        .aiDefaultModel: "Local AI connections, credentials, instructions and histories.",
        .aiWebSearch: "Local AI connections, credentials, instructions and histories.",
        .aiSystemPrompt: "Local AI connections, credentials, instructions and histories.",
        .aiSystemPromptEnabled: "Local AI connections, credentials, instructions and histories.",
        .aiRetention: "Local AI connections, credentials, instructions and histories.",
        .aiOpensTo: "Local AI connections, credentials, instructions and histories.",
        .aiNewChatAfter: "Local AI connections, credentials, instructions and histories.",
        .mcpEnabled: "Local executable servers and credentials.",
        .mcpServers: "Local executable servers and credentials.",
        .quickActionsEnabled: "Local text delivery consent and AI transformation policy.",
        .quickActionModel: "Local text delivery consent and AI transformation policy.",
        .quickActionPreviews: "Local text delivery consent and AI transformation policy.",
        .quickActionInstructions: "Local text delivery consent and AI transformation policy.",
        .quickActionLanguage: "Local text delivery consent and AI transformation policy."
    ]
}
